

module.exports = {
  	NEW_BLOG: 'NEW_BLOG',
  	EDIT_BLOG: 'EDIT_BLOG',
  	REMOVE_BLOG: 'REMOVE_BLOG',
  	GET_BLOG: 'GET_BLOG',
  	GET_BLOG_RESPONSE: 'GET_BLOG_RESPONSE',
  	GET_SERVER_RESPONSE: 'GET_SERVER_RESPONSE',
  	EDIT_FORM_VISIBLE: 'EDIT_FORM_VISIBLE',
  	EXPAND: 'EXPAND'
};